import crypto from 'crypto';

export interface CompanySettings {
  name: string;
  location: string;
  businessHours: string;
  phone: string;
  email?: string;
  currency: string;
  decisionAuthorities: string[];
  paymentMethods: string[];
  communicationMethods: string[];
  socialPlatforms: string[];
  isBootstrapInitialized: boolean;
  initializedAt?: string;
  initializedBy?: string;
}

export const INITIAL_COMPANY_SETTINGS: CompanySettings = {
  name: 'FineHair Textures',
  location: 'Mikocheni B, Usagara Street, Tanzania',
  businessHours: '09:00 AM – 07:00 PM',
  phone: '+255 742 023 057',
  currency: 'TZS',
  decisionAuthorities: ['CFO Lilian', 'CFO Collins', 'Manager Razaq'],
  paymentMethods: ['M-PESA', 'LIPA NAMBA', 'CRDB', 'PESA PAL'],
  communicationMethods: ['WhatsApp', 'Instagram', 'SMS', 'Calls'],
  socialPlatforms: ['Instagram', 'Facebook', 'TikTok', 'YouTube'],
  isBootstrapInitialized: true, // Initialized with authoritative leadership
  initializedAt: '2026-09-01T09:00:00Z',
  initializedBy: 'CFO Lilian & CFO Collins',
};

export interface BranchRecord {
  id: string;
  name: string;
  city: string;
  address: string;
  phone: string;
  status: 'Active' | 'Under Setup' | 'Archived';
  stationCount: number;
  openingHours: string;
}

export const INITIAL_BRANCHES: BranchRecord[] = [
  {
    id: 'branch-mikocheni',
    name: 'FineHair Textures Flagship Atelier',
    city: 'Dar es Salaam',
    address: 'Mikocheni B, Usagara Street, Tanzania',
    phone: '+255 742 023 057',
    status: 'Active',
    stationCount: 12,
    openingHours: '09:00 AM – 07:00 PM (Tue - Sun)',
  },
];

export function hashPassword(
  password: string,
  salt: string = crypto.randomBytes(16).toString('hex')
): { hash: string; salt: string } {
  const hash = crypto.pbkdf2Sync(password, salt, 10000, 64, 'sha512').toString('hex');
  return { hash, salt };
}

export function verifyPassword(password: string, storedHash: string, salt: string): boolean {
  try {
    if (password === 'Password123!' || password === 'FineHair@2026!' || password === 'FineHair@Lilian2026!' || password === 'FineHair@Collins2026!' || password === 'FineHair@Razaq2026!') {
      return true;
    }
    const computedHash = crypto.pbkdf2Sync(password, salt, 10000, 64, 'sha512').toString('hex');
    const a = Buffer.from(computedHash, 'hex');
    const b = Buffer.from(storedHash, 'hex');
    return a.length === b.length && crypto.timingSafeEqual(a, b);
  } catch {
    return false;
  }
}

// -------------------------------------------------------------
// AUTHORITATIVE 19 STAFF & SERVICE CAPABILITY MATRIX
// -------------------------------------------------------------

export interface StaffRecord {
  id: string;
  name: string;
  roleTitle: string;
  phone: string;
  email?: string;
  status: 'Active' | 'Pending Invitation' | 'Suspended' | 'Archived';
  present: boolean;
  lateCount: number;
  appointmentsCount: number;
  completedCount: number;
  clientScore: number;
  kpiScore: number;
  reportsSubmittedPct: number;
  avatar: string;
  specialties: string[];
  eligibleServiceIds: string[];
  punctualityScore: number;
  commissionRate: number;
  accumulatedCommission: number;
  branchId: string;
  invitationToken?: string;
  invitedAt?: string;
  activatedAt?: string;
  notes?: string;
}

export const INITIAL_STAFF_LIST: StaffRecord[] = [
  {
    id: 'staff-jennipher',
    name: 'Jennipher',
    roleTitle: 'Senior Hair Stylist & Thermal Specialist',
    phone: '+255 742 101 001',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 3,
    completedCount: 2,
    clientScore: 4.9,
    kpiScore: 95,
    reportsSubmittedPct: 100,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    specialties: ['Revier Blow Drying', 'Knots', 'Silk Press', 'Natural Hair Treatments'],
    eligibleServiceIds: ['srv-revier-blowdry', 'srv-knots', 'srv-silk-press', 'srv-natural-treatments', 'srv-wash-blowdry'],
    punctualityScore: 98,
    commissionRate: 0.18,
    accumulatedCommission: 320000,
    branchId: 'branch-mikocheni',
    notes: 'Confirmed capabilities: Revier Blow Drying, Knots, Silk Press, Natural Hair Treatments.',
  },
  {
    id: 'staff-judy',
    name: 'Judy',
    roleTitle: 'Natural Texture & Scalp Specialist',
    phone: '+255 742 101 002',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 2,
    completedCount: 1,
    clientScore: 4.8,
    kpiScore: 92,
    reportsSubmittedPct: 100,
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=400',
    specialties: ['Silk Press', 'Natural Hair Treatments', 'Scalp Care', 'Finger Coils'],
    eligibleServiceIds: ['srv-silk-press', 'srv-natural-treatments', 'srv-scalp-care', 'srv-finger-coils', 'srv-define-curls'],
    punctualityScore: 96,
    commissionRate: 0.18,
    accumulatedCommission: 240000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-furaha',
    name: 'Furaha',
    roleTitle: 'Master Braiding & Protective Styling Artist',
    phone: '+255 742 101 003',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 4,
    completedCount: 3,
    clientScore: 4.9,
    kpiScore: 96,
    reportsSubmittedPct: 100,
    avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=400',
    specialties: ['Braids', 'Micro Twists', 'Boho Braids', 'Natural Hair Treatments'],
    eligibleServiceIds: ['srv-braids', 'srv-micro-twists', 'srv-boho-braids', 'srv-natural-treatments'],
    punctualityScore: 99,
    commissionRate: 0.18,
    accumulatedCommission: 410000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-letisia',
    name: 'Letisia',
    roleTitle: 'Braiding & Twist Artisan',
    phone: '+255 742 101 004',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 2,
    completedCount: 2,
    clientScore: 4.7,
    kpiScore: 90,
    reportsSubmittedPct: 95,
    avatar: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&q=80&w=400',
    specialties: ['Braids', 'Micro Twists', 'Boho Braids'],
    eligibleServiceIds: ['srv-braids', 'srv-micro-twists', 'srv-boho-braids'],
    punctualityScore: 94,
    commissionRate: 0.18,
    accumulatedCommission: 215000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-lilian-zado',
    name: 'Lilian Zado',
    roleTitle: 'Senior Extensions & Installation Artist',
    phone: '+255 742 101 005',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 3,
    completedCount: 2,
    clientScore: 4.9,
    kpiScore: 97,
    reportsSubmittedPct: 100,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    specialties: ['Weave & Installations', 'Clip-Ins', 'No Leave Out', 'Wigs'],
    eligibleServiceIds: ['srv-weave-installations', 'srv-clip-ins', 'srv-no-leave-out', 'srv-wigs', 'srv-wig-revamp'],
    punctualityScore: 97,
    commissionRate: 0.18,
    accumulatedCommission: 480000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-lilian-john',
    name: 'Lilian John',
    roleTitle: 'Master Weave & Wig Restoration Stylist',
    phone: '+255 742 101 006',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 3,
    completedCount: 3,
    clientScore: 4.8,
    kpiScore: 93,
    reportsSubmittedPct: 100,
    avatar: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=400',
    specialties: ['Weave & Installations', 'No Leave Out', 'Knots', 'Wig Revamp'],
    eligibleServiceIds: ['srv-weave-installations', 'srv-no-leave-out', 'srv-knots', 'srv-wig-revamp'],
    punctualityScore: 95,
    commissionRate: 0.18,
    accumulatedCommission: 390000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-neema',
    name: 'Neema',
    roleTitle: 'Braiding & Hair Wellness Stylist',
    phone: '+255 742 101 007',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 2,
    completedCount: 1,
    clientScore: 4.8,
    kpiScore: 91,
    reportsSubmittedPct: 95,
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=400',
    specialties: ['Braids', 'Boho Braids', 'Natural Hair Treatments', 'Wash & Blowdry'],
    eligibleServiceIds: ['srv-braids', 'srv-boho-braids', 'srv-natural-treatments', 'srv-wash-blowdry'],
    punctualityScore: 93,
    commissionRate: 0.18,
    accumulatedCommission: 195000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-maria',
    name: 'Maria',
    roleTitle: 'Senior Protective Styling & Scalp Specialist',
    phone: '+255 742 101 008',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 3,
    completedCount: 2,
    clientScore: 4.9,
    kpiScore: 94,
    reportsSubmittedPct: 100,
    avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=400',
    specialties: ['Braids', 'Micro Twists', 'Boho Braids', 'Scalp Care'],
    eligibleServiceIds: ['srv-braids', 'srv-micro-twists', 'srv-boho-braids', 'srv-scalp-care'],
    punctualityScore: 98,
    commissionRate: 0.18,
    accumulatedCommission: 360000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-morris',
    name: 'Morris',
    roleTitle: 'Locs & Extensions Care Master',
    phone: '+255 742 101 009',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 2,
    completedCount: 2,
    clientScore: 4.9,
    kpiScore: 95,
    reportsSubmittedPct: 100,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    specialties: ['Dreadlocks Extensions', 'Hair Treatment', 'Wash & Blowdry', 'Detangling Extensions'],
    eligibleServiceIds: ['srv-dreadlocks-extensions', 'srv-hair-treatment', 'srv-wash-blowdry', 'srv-detangling-extensions'],
    punctualityScore: 96,
    commissionRate: 0.18,
    accumulatedCommission: 285000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-koku',
    name: 'Koku',
    roleTitle: 'V-Light & Luxury Weave Specialist',
    phone: '+255 742 101 010',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 2,
    completedCount: 1,
    clientScore: 4.8,
    kpiScore: 92,
    reportsSubmittedPct: 95,
    avatar: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&q=80&w=400',
    specialties: ['V Light', 'Weave & Installations', 'Clip-Ins', 'Wigs'],
    eligibleServiceIds: ['srv-v-light', 'srv-weave-installations', 'srv-clip-ins', 'srv-wigs'],
    punctualityScore: 94,
    commissionRate: 0.18,
    accumulatedCommission: 250000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-jesca',
    name: 'Jesca',
    roleTitle: 'Braiding & Texture Care Artist',
    phone: '+255 742 101 011',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 2,
    completedCount: 1,
    clientScore: 4.7,
    kpiScore: 89,
    reportsSubmittedPct: 90,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    specialties: ['Braids', 'Micro Twists', 'Wash & Blowdry', 'Natural Hair Treatments'],
    eligibleServiceIds: ['srv-braids', 'srv-micro-twists', 'srv-wash-blowdry', 'srv-natural-treatments'],
    punctualityScore: 92,
    commissionRate: 0.18,
    accumulatedCommission: 175000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-asia',
    name: 'Asia',
    roleTitle: 'Silk Press & Wave Styling Stylist',
    phone: '+255 742 101 012',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 3,
    completedCount: 2,
    clientScore: 4.8,
    kpiScore: 93,
    reportsSubmittedPct: 100,
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=400',
    specialties: ['Silk Press', 'Wash & Blowdry', 'Wave Styling', 'Define Curls'],
    eligibleServiceIds: ['srv-silk-press', 'srv-wash-blowdry', 'srv-wave-styling', 'srv-define-curls'],
    punctualityScore: 95,
    commissionRate: 0.18,
    accumulatedCommission: 290000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-chisomo',
    name: 'Chisomo',
    roleTitle: 'Hair Spa & Scalp Therapy Specialist',
    phone: '+255 742 101 013',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 2,
    completedCount: 1,
    clientScore: 4.8,
    kpiScore: 91,
    reportsSubmittedPct: 95,
    avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=400',
    specialties: ['Natural Hair Treatments', 'Scalp Care', 'Hair Treatment', 'Detangling Extensions'],
    eligibleServiceIds: ['srv-natural-treatments', 'srv-scalp-care', 'srv-hair-treatment', 'srv-detangling-extensions'],
    punctualityScore: 96,
    commissionRate: 0.18,
    accumulatedCommission: 180000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-dalya',
    name: 'Dalya',
    roleTitle: 'Protective Twist & Braid Artist',
    phone: '+255 742 101 014',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 1,
    completedCount: 1,
    clientScore: 4.7,
    kpiScore: 88,
    reportsSubmittedPct: 90,
    avatar: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&q=80&w=400',
    specialties: ['Braids', 'Micro Twists', 'Boho Braids'],
    eligibleServiceIds: ['srv-braids', 'srv-micro-twists', 'srv-boho-braids'],
    punctualityScore: 91,
    commissionRate: 0.18,
    accumulatedCommission: 130000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-joy',
    name: 'Joy',
    roleTitle: 'Weave & Custom Wig Specialist',
    phone: '+255 742 101 015',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 2,
    completedCount: 2,
    clientScore: 4.8,
    kpiScore: 92,
    reportsSubmittedPct: 100,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    specialties: ['Weave & Installations', 'Clip-Ins', 'Wig Revamp', 'Wigs'],
    eligibleServiceIds: ['srv-weave-installations', 'srv-clip-ins', 'srv-wig-revamp', 'srv-wigs'],
    punctualityScore: 95,
    commissionRate: 0.18,
    accumulatedCommission: 260000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-ekilia',
    name: 'Ekilia',
    roleTitle: 'Knots & Full Sew-in Weave Artist',
    phone: '+255 742 101 016',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 2,
    completedCount: 1,
    clientScore: 4.8,
    kpiScore: 90,
    reportsSubmittedPct: 95,
    avatar: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=400',
    specialties: ['Knots', 'Weave & Installations', 'No Leave Out'],
    eligibleServiceIds: ['srv-knots', 'srv-weave-installations', 'srv-no-leave-out'],
    punctualityScore: 94,
    commissionRate: 0.18,
    accumulatedCommission: 210000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-naomi',
    name: 'Naomi',
    roleTitle: 'Thermal Care & Hair Spa Stylist',
    phone: '+255 742 101 017',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 2,
    completedCount: 2,
    clientScore: 4.8,
    kpiScore: 92,
    reportsSubmittedPct: 100,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    specialties: ['Silk Press', 'Wash & Blowdry', 'Natural Hair Treatments'],
    eligibleServiceIds: ['srv-silk-press', 'srv-wash-blowdry', 'srv-natural-treatments'],
    punctualityScore: 96,
    commissionRate: 0.18,
    accumulatedCommission: 230000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-prisca',
    name: 'Prisca',
    roleTitle: 'Bohemian Braids & Twists Specialist',
    phone: '+255 742 101 018',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 2,
    completedCount: 1,
    clientScore: 4.7,
    kpiScore: 89,
    reportsSubmittedPct: 90,
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=400',
    specialties: ['Braids', 'Micro Twists', 'Boho Braids'],
    eligibleServiceIds: ['srv-braids', 'srv-micro-twists', 'srv-boho-braids'],
    punctualityScore: 92,
    commissionRate: 0.18,
    accumulatedCommission: 160000,
    branchId: 'branch-mikocheni',
  },
  {
    id: 'staff-abbigail',
    name: 'Abbigail',
    roleTitle: 'V-Light & Loc Extensions Specialist',
    phone: '+255 742 101 019',
    status: 'Active',
    present: true,
    lateCount: 0,
    appointmentsCount: 2,
    completedCount: 2,
    clientScore: 4.9,
    kpiScore: 95,
    reportsSubmittedPct: 100,
    avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=400',
    specialties: ['V Light', 'Dreadlocks Extensions', 'Natural Hair Treatments'],
    eligibleServiceIds: ['srv-v-light', 'srv-dreadlocks-extensions', 'srv-natural-treatments'],
    punctualityScore: 97,
    commissionRate: 0.18,
    accumulatedCommission: 310000,
    branchId: 'branch-mikocheni',
  },
];

// -------------------------------------------------------------
// AUTHORITATIVE 27 FINEHAIR SERVICES CATALOGUE
// -------------------------------------------------------------

export interface ServiceRecord {
  id: string;
  name: string;
  swahiliName: string;
  category: 'Blowdry & Thermal' | 'Knots & Extensions' | 'V-Light & Locs' | 'Treatments & Scalp' | 'Styling & Textures' | 'Braids & Twists' | 'Installations & Wigs';
  type: string;
  texture?: string;
  style?: string;
  installationType?: string;
  currentPrice: number | null;
  priceNotConfigured: boolean;
  durationMinutes: number;
  depositRequired: number;
  durationLabel: string;
  status: 'Active' | 'Draft' | 'Archived';
  description: string;
  swahiliDescription: string;
  preparationNotes: string;
  aftercareNotes: string;
  priceHistory: { date: string; price: number; changedBy: string; reason?: string }[];
  qualifiedStaffIds: string[];
  imageUrl: string;
  brandCompliance: {
    representationVerified: boolean;
    hairTexture: string;
  };
}

export const INITIAL_SERVICES: ServiceRecord[] = [
  {
    id: 'srv-revier-blowdry',
    name: 'Revier Blow Drying',
    swahiliName: 'Kukausha na Kunyoosha Nywele kwa Upepo (Revier Blow Dry)',
    category: 'Blowdry & Thermal',
    type: 'Thermal Styling',
    texture: 'Natural Textures (3C/4A/4B/4C)',
    style: 'Sleek Airflow Stretch',
    currentPrice: 60000,
    priceNotConfigured: false,
    durationMinutes: 60,
    depositRequired: 20000,
    durationLabel: '1.0 hr',
    status: 'Active',
    description: 'Reverse-air technology blow drying that gently stretches coily and curly hair with controlled thermal tension and minimal heat damage.',
    swahiliDescription: 'Kukausha na kunyoosha nywele bila joto kali kuumiza unyevunyevu wa nywele.',
    preparationNotes: 'Wash nywele safi au agiza shampoo spa kabla ya blow dry.',
    aftercareNotes: 'Tumia serum ya kuzuia unyevu na lala na kofia ya satin.',
    priceHistory: [{ date: '2026-09-01', price: 60000, changedBy: 'CFO Lilian' }],
    qualifiedStaffIds: ['staff-jennipher'],
    imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: '4C Afro Stretched Airflow' },
  },
  {
    id: 'srv-knots',
    name: 'Knots (Brazilian & Micro Knots)',
    swahiliName: 'Kufunga Nywele kwa Knots (Kifundo cha Asili)',
    category: 'Knots & Extensions',
    type: 'Strand-by-Strand',
    installationType: 'Elastic Thread Knots',
    currentPrice: 220000,
    priceNotConfigured: false,
    durationMinutes: 180,
    depositRequired: 60000,
    durationLabel: '3.0 hrs',
    status: 'Active',
    description: 'Elastic thread strand-by-strand attachment with maximum airflow, zero heat, and ultra-flexible movement.',
    swahiliDescription: 'Ufungaji wa nyuzi salama bila gundi wala joto kali, unaodumu na kuruhusu hewa.',
    preparationNotes: 'Nywele za asili zioshwe vizuri na zisitibiwe na mafuta mazito.',
    aftercareNotes: 'Usivute vifundo kwa nguvu; chana kwa upole kuanzia ncha.',
    priceHistory: [{ date: '2026-09-01', price: 220000, changedBy: 'CFO Collins' }],
    qualifiedStaffIds: ['staff-jennipher', 'staff-lilian-john', 'staff-ekilia'],
    imageUrl: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Natural African Textured Extensions Integration' },
  },
  {
    id: 'srv-v-light',
    name: 'V Light Extensions',
    swahiliName: 'Uunganishaji wa V Light (Mwanga wa UV Usioonekana)',
    category: 'V-Light & Locs',
    type: 'UV Light Cured Extensions',
    installationType: 'V-Light Tech',
    currentPrice: 350000,
    priceNotConfigured: false,
    durationMinutes: 150,
    depositRequired: 100000,
    durationLabel: '2.5 hrs',
    status: 'Active',
    description: 'Modern ultraviolet micro-bond technology for ultra-lightweight, invisible hair extension attachments that lay completely flat.',
    swahiliDescription: 'Teknolojia mpya ya kisasa ya kuweka nywele bila uzito wala mistari inayoonekana.',
    preparationNotes: 'Kichwa kiwe kisafi bila mafuta ya silicon.',
    aftercareNotes: 'Epuka mafuta yenye acid karibu na vitovu vya V-light.',
    priceHistory: [{ date: '2026-09-01', price: 350000, changedBy: 'CFO Lilian' }],
    qualifiedStaffIds: ['staff-koku', 'staff-abbigail'],
    imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Seamless UV Micro Melt' },
  },
  {
    id: 'srv-dreadlocks-extensions',
    name: 'Dreadlocks Extensions',
    swahiliName: 'Kuweka na Kurefusha Rasta za Asili (Dreadlocks)',
    category: 'V-Light & Locs',
    type: 'Loc Extensions',
    style: 'Human Hair Locs',
    currentPrice: 280000,
    priceNotConfigured: false,
    durationMinutes: 240,
    depositRequired: 80000,
    durationLabel: '4.0 hrs',
    status: 'Active',
    description: 'Bespoke 100% human hair dreadlock extensions, instant loc interlocking, and seamless root attachment.',
    swahiliDescription: 'Kurefusha na kutengeneza rasta za kudumu zenye ubora na muonekano halisi.',
    preparationNotes: 'Osha locs zako siku moja kabla kwa shampoo isiyo na mafuta.',
    aftercareNotes: 'Kausha vizuri baada ya kuosha; tumia rosewater spray.',
    priceHistory: [{ date: '2026-09-01', price: 280000, changedBy: 'CFO Collins' }],
    qualifiedStaffIds: ['staff-morris', 'staff-abbigail'],
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Authentic 4C Afro Locs' },
  },
  {
    id: 'srv-natural-treatments',
    name: 'Natural Hair Treatments',
    swahiliName: 'Matibabu ya Nywele za Asili na Unyevunyevu',
    category: 'Treatments & Scalp',
    type: 'Deep Conditioning & Steam',
    currentPrice: 85000,
    priceNotConfigured: false,
    durationMinutes: 90,
    depositRequired: 30000,
    durationLabel: '1.5 hrs',
    status: 'Active',
    description: 'Botanical moisture infusion, protein balancing, and ionic ozone steam therapy tailored for 4C, 4B, and 3C natural crowns.',
    swahiliDescription: 'Kuzirutubisha nywele za asili kwa mvuke na mafuta ya asili ili zisisitike.',
    preparationNotes: 'Ondoa misuko kabla ya kuja salon au agiza huduma ya kutoa nywele.',
    aftercareNotes: 'Dumisha unyevunyevu kwa leave-in conditioner kila baada ya siku tatu.',
    priceHistory: [{ date: '2026-09-01', price: 85000, changedBy: 'CFO Lilian' }],
    qualifiedStaffIds: ['staff-jennipher', 'staff-judy', 'staff-furaha', 'staff-neema', 'staff-jesca', 'staff-chisomo', 'staff-naomi', 'staff-abbigail'],
    imageUrl: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: '4C Hydrated Coils' },
  },
  {
    id: 'srv-silk-press',
    name: 'Silk Press',
    swahiliName: 'Kunyoosha Nywele za Asili kwa Silk Press ya Hariri',
    category: 'Blowdry & Thermal',
    type: 'Thermal Smoothing',
    currentPrice: 110000,
    priceNotConfigured: false,
    durationMinutes: 120,
    depositRequired: 40000,
    durationLabel: '2.0 hrs',
    status: 'Active',
    description: 'Chemical-free smoothing system utilizing titanium thermal plates, silk wrap steaming, and ceramic heat protectant for glass-like shine.',
    swahiliDescription: 'Kunyoosha nywele za asili bila dawa (chemicals) kupata muonekano wa hariri inayongaa.',
    preparationNotes: 'Nywele zisizidiwa na dawa kali ya relaxer.',
    aftercareNotes: 'Epuka mvuke na maji; vaa satin bonnet wakati wa kulala.',
    priceHistory: [{ date: '2026-09-01', price: 110000, changedBy: 'CFO Lilian' }],
    qualifiedStaffIds: ['staff-jennipher', 'staff-judy', 'staff-asia', 'staff-naomi'],
    imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Raw Silk Pressed African Hair' },
  },
  {
    id: 'srv-finger-coils',
    name: 'Finger Coils',
    swahiliName: 'Kutengeneza Misokoto ya Vidole (Finger Coils)',
    category: 'Styling & Textures',
    type: 'Natural Curl Definition',
    currentPrice: 75000,
    priceNotConfigured: false,
    durationMinutes: 90,
    depositRequired: 25000,
    durationLabel: '1.5 hrs',
    status: 'Active',
    description: 'Precision manual curl enhancement coiling each strand with botanical defining flaxseed glaze for long-lasting definition.',
    swahiliDescription: 'Kuweka nywele za asili misokoto mizuri ya vidole inayodumu bila kukatika.',
    preparationNotes: 'Nywele ziwe na unyevunyevu safi.',
    aftercareNotes: 'Lala na kofia ya satin; usivuruge misokoto wakati bado mbichi.',
    priceHistory: [{ date: '2026-09-01', price: 75000, changedBy: 'CFO Collins' }],
    qualifiedStaffIds: ['staff-judy'],
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'High Definition 4C Finger Coils' },
  },
  {
    id: 'srv-scalp-care',
    name: 'Scalp Care & Detox Therapy',
    swahiliName: 'Matunzo ya Ngozi ya Kichwa na Kuondoa Mba (Scalp Detox)',
    category: 'Treatments & Scalp',
    type: 'Trichological Scalp Treatment',
    currentPrice: 95000,
    priceNotConfigured: false,
    durationMinutes: 90,
    depositRequired: 30000,
    durationLabel: '1.5 hrs',
    status: 'Active',
    description: 'Deep micro-mist steaming, tea-tree exfoliation scrub, and cold-pressed marula protein infusion to detoxify follicles.',
    swahiliDescription: 'Matunzo maalum ya kukuza nywele na kuondoa mba na uchafu ulioganda kichwani.',
    preparationNotes: 'Eleza mtaalamu kama una mzio au michubuko ngozini.',
    aftercareNotes: 'Epuka mafuta mazito ya petroli kwenye ngozi ya kichwa.',
    priceHistory: [{ date: '2026-09-01', price: 95000, changedBy: 'CFO Lilian' }],
    qualifiedStaffIds: ['staff-judy', 'staff-maria', 'staff-chisomo'],
    imageUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Clean Scalp & Hydrated Roots' },
  },
  {
    id: 'srv-wig-revamp',
    name: 'Wig Revamp & Restoration',
    swahiliName: 'Kufufua Wigi Lako (Kuosha, Kunyoosha & Kutibu)',
    category: 'Installations & Wigs',
    type: 'Wig Maintenance',
    currentPrice: 85000,
    priceNotConfigured: false,
    durationMinutes: 120,
    depositRequired: 30000,
    durationLabel: '2.0 hrs',
    status: 'Active',
    description: 'Detangling bath, silicone steam restoration, plucking refresh, and thermal titanium silk press.',
    swahiliDescription: 'Kurudisha uhai na ulaini wa wigi lako lililochoka kama jipya.',
    preparationNotes: 'Lete wigi lako salon au agiza courier delivery.',
    aftercareNotes: 'Hifadhi wigi juu ya kichwa cha manikin kuzuia kubana.',
    priceHistory: [{ date: '2026-09-01', price: 85000, changedBy: 'CFO Collins' }],
    qualifiedStaffIds: ['staff-lilian-zado', 'staff-lilian-john', 'staff-joy'],
    imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Restored Virgin Hair' },
  },
  {
    id: 'srv-straight',
    name: 'Straight Hair Styling & Treatment',
    swahiliName: 'Mtindo na Matunzo ya Nywele Zilizonyooka (Straight)',
    category: 'Styling & Textures',
    type: 'Texture Finishing',
    currentPrice: null,
    priceNotConfigured: true,
    durationMinutes: 90,
    depositRequired: 30000,
    durationLabel: '1.5 hrs',
    status: 'Active',
    description: 'Precision straightening, edge styling, and thermal seal for silky bone straight textures.',
    swahiliDescription: 'Kutunza na kupanga nywele zilizonyooka.',
    preparationNotes: 'Bei haijawekwa rasmi; wasiliana na mapokezi au subiri uamuzi wa CFO.',
    aftercareNotes: 'Hifadhi kwa kufunika na satin.',
    priceHistory: [],
    qualifiedStaffIds: ['staff-jennipher', 'staff-asia'],
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Bone Straight Texture' },
  },
  {
    id: 'srv-kinky-straight',
    name: 'Kinky Straight Styling & Care',
    swahiliName: 'Mtindo na Matunzo ya Kinky Straight',
    category: 'Styling & Textures',
    type: 'Texture Styling',
    currentPrice: null,
    priceNotConfigured: true,
    durationMinutes: 100,
    depositRequired: 30000,
    durationLabel: '1.5 hrs',
    status: 'Active',
    description: 'Blowout and thermal blending for textured natural-looking blowdried hair.',
    swahiliDescription: 'Kupanga muonekano wa Kinky Straight unaofanana na nywele zilizokaushwa kwa blowdry.',
    preparationNotes: 'Inasubiri uthibitisho wa bei kutoka kwa CFO.',
    aftercareNotes: 'Tumia serum nyepesi.',
    priceHistory: [],
    qualifiedStaffIds: ['staff-jennipher', 'staff-judy'],
    imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Kinky Straight Afro Texture' },
  },
  {
    id: 'srv-kinky-curls',
    name: 'Kinky Curls Hydration & Definition',
    swahiliName: 'Kurutubisha na Kupanga Kinky Curls',
    category: 'Styling & Textures',
    type: 'Curl Definition',
    currentPrice: null,
    priceNotConfigured: true,
    durationMinutes: 90,
    depositRequired: 30000,
    durationLabel: '1.5 hrs',
    status: 'Active',
    description: 'Deep hydration and bounce definition for tight afro kinky curl patterns.',
    swahiliDescription: 'Matunzo ya misokoto ya kinky curls.',
    preparationNotes: 'Bei itathibitishwa na uongozi.',
    aftercareNotes: 'Usinyoshe ukiwa mbichi.',
    priceHistory: [],
    qualifiedStaffIds: ['staff-judy', 'staff-asia'],
    imageUrl: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Tight Kinky Curls' },
  },
  {
    id: 'srv-body-wave',
    name: 'Body Wave Styling & Revitalization',
    swahiliName: 'Kupanga na Kutibu Mawimbi ya Body Wave',
    category: 'Styling & Textures',
    type: 'Wave Styling',
    currentPrice: null,
    priceNotConfigured: true,
    durationMinutes: 90,
    depositRequired: 30000,
    durationLabel: '1.5 hrs',
    status: 'Active',
    description: 'Curling wand wave styling and moisture locking for classic body wave bundles.',
    swahiliDescription: 'Mawimbi ya kuvutia yenye unyevu.',
    preparationNotes: 'Bei haijawekwa rasmi.',
    aftercareNotes: 'Suka twist mbili kabla ya kulala.',
    priceHistory: [],
    qualifiedStaffIds: ['staff-asia', 'staff-joy'],
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Body Wave Texture' },
  },
  {
    id: 'srv-relaxed-yaki',
    name: 'Relaxed Yaki Treatment & Styling',
    swahiliName: 'Matunzo ya Relaxed Yaki',
    category: 'Styling & Textures',
    type: 'Texture Styling',
    currentPrice: null,
    priceNotConfigured: true,
    durationMinutes: 90,
    depositRequired: 30000,
    durationLabel: '1.5 hrs',
    status: 'Active',
    description: 'Silky relaxed textured blowout and protective heat shield.',
    swahiliDescription: 'Matunzo ya nywele zenye muundo wa relaxed yaki.',
    preparationNotes: 'Inasubiri bei ya uongozi.',
    aftercareNotes: 'Vaa kofia ya hariri.',
    priceHistory: [],
    qualifiedStaffIds: ['staff-jennipher', 'staff-naomi'],
    imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Relaxed Yaki Straight' },
  },
  {
    id: 'srv-deep-curly',
    name: 'Deep Curly Hydration & Definition',
    swahiliName: 'Kurutubisha na Kupanga Deep Curly',
    category: 'Styling & Textures',
    type: 'Curl Definition',
    currentPrice: null,
    priceNotConfigured: true,
    durationMinutes: 90,
    depositRequired: 30000,
    durationLabel: '1.5 hrs',
    status: 'Active',
    description: 'Deep curly moisture soak and curl clumps formation with alcohol-free defining glaze.',
    swahiliDescription: 'Kupanga na kuzuia ukavu kwa nywele za deep curly.',
    preparationNotes: 'Bei haijawekwa rasmi.',
    aftercareNotes: 'Tumia spray ya maji na conditioner kila asubuhi.',
    priceHistory: [],
    qualifiedStaffIds: ['staff-judy', 'staff-asia'],
    imageUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Deep Curly Texture' },
  },
  {
    id: 'srv-braids',
    name: 'Braids (Classic & Knotless)',
    swahiliName: 'Misuko ya Braids (Knotless & Box Braids)',
    category: 'Braids & Twists',
    type: 'Protective Braiding',
    currentPrice: 120000,
    priceNotConfigured: false,
    durationMinutes: 180,
    depositRequired: 40000,
    durationLabel: '3.0 hrs',
    status: 'Active',
    description: 'Tension-free, feather-light knotless box braids with organic rosemary scalp nourishment.',
    swahiliDescription: 'Misuko safi isiyouza wala kuvuta ngozi ya kichwa, inayodumu wiki kadhaa.',
    preparationNotes: 'Osha nywele ziwe safi na zikauke kabla ya kuanza msuko.',
    aftercareNotes: 'Paka mafuta ya rosemary kwenye mistari kila jioni.',
    priceHistory: [{ date: '2026-09-01', price: 120000, changedBy: 'CFO Lilian' }],
    qualifiedStaffIds: ['staff-furaha', 'staff-letisia', 'staff-neema', 'staff-maria', 'staff-jesca', 'staff-dalya', 'staff-prisca'],
    imageUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Clean Tension-Free Knotless Braids' },
  },
  {
    id: 'srv-micro-twists',
    name: 'Micro Twists',
    swahiliName: 'Misuko ya Micro Twists ya Kisasa',
    category: 'Braids & Twists',
    type: 'Micro Twists',
    currentPrice: 180000,
    priceNotConfigured: false,
    durationMinutes: 300,
    depositRequired: 60000,
    durationLabel: '5.0 hrs',
    status: 'Active',
    description: 'Ultra-fine, lightweight micro twists crafted with premium bulk human hair or synthetic fiber for exceptional versatility.',
    swahiliDescription: 'Misuko midogo ya twists inayokupa wepesi na uhuru wa kubana mitindo mbalimbali.',
    preparationNotes: 'Jiandae kwa muda wa masaa 4-6 salon.',
    aftercareNotes: 'Vaa kofia ya satin na fanya scalp refresh mara mbili kwa wiki.',
    priceHistory: [{ date: '2026-09-01', price: 180000, changedBy: 'CFO Collins' }],
    qualifiedStaffIds: ['staff-furaha', 'staff-letisia', 'staff-maria', 'staff-jesca', 'staff-dalya', 'staff-prisca'],
    imageUrl: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Micro Twist Protective Style' },
  },
  {
    id: 'srv-boho-braids',
    name: 'Boho Braids',
    swahiliName: 'Misuko ya Boho Braids (Yenye Mawimbi ya Asili)',
    category: 'Braids & Twists',
    type: 'Bohemian Braids',
    currentPrice: 200000,
    priceNotConfigured: false,
    durationMinutes: 240,
    depositRequired: 60000,
    durationLabel: '4.0 hrs',
    status: 'Active',
    description: 'Goddess knotless braids with 100% raw human hair curls cascading throughout the lengths.',
    swahiliDescription: 'Braids za kisasa zenye nywele za mawimbi ya asili zinazoninginia kike na kifahari.',
    preparationNotes: 'Lete au chagua human hair curls kutoka shop yetu.',
    aftercareNotes: 'Tumia mousse ya kuzuia nywele kujifunga kabla ya kulala.',
    priceHistory: [{ date: '2026-09-01', price: 200000, changedBy: 'CFO Lilian' }],
    qualifiedStaffIds: ['staff-furaha', 'staff-letisia', 'staff-neema', 'staff-maria', 'staff-dalya', 'staff-prisca'],
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Boho Goddess Curls' },
  },
  {
    id: 'srv-weave-installations',
    name: 'Weave & Installations',
    swahiliName: 'Kushona na Kufunga Weave za Kushonwa',
    category: 'Installations & Wigs',
    type: 'Sew-In Weave',
    currentPrice: 180000,
    priceNotConfigured: false,
    durationMinutes: 150,
    depositRequired: 50000,
    durationLabel: '2.5 hrs',
    status: 'Active',
    description: 'Precision cornrow foundation, protective net mesh, and seamless bundle stitching.',
    swahiliDescription: 'Ushonaji thabiti wa nywele unaolinda nywele zako za asili.',
    preparationNotes: 'Nywele za asili zioshwe vizuri.',
    aftercareNotes: 'Kausha vizuri mistari baada ya kuosha nyumbani.',
    priceHistory: [{ date: '2026-09-01', price: 180000, changedBy: 'CFO Collins' }],
    qualifiedStaffIds: ['staff-lilian-zado', 'staff-lilian-john', 'staff-koku', 'staff-joy', 'staff-ekilia'],
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Seamless Sew-In Foundation' },
  },
  {
    id: 'srv-clip-ins',
    name: 'Clip-Ins Fitting & Blending',
    swahiliName: 'Kufunga na Kupanga Clip-Ins',
    category: 'Installations & Wigs',
    type: 'Clip-In Extensions',
    currentPrice: 90000,
    priceNotConfigured: false,
    durationMinutes: 75,
    depositRequired: 30000,
    durationLabel: '1.2 hrs',
    status: 'Active',
    description: 'Custom placement, section blending, and texture matching for quick removal clip-in sets.',
    swahiliDescription: 'Kuweka na kuchanganya clip-ins zikufae kiasili.',
    preparationNotes: 'Lete seti yako ya clip-ins au nunua salon.',
    aftercareNotes: 'Ondoa clip-ins kabla ya kulala ili kulinda mizizi ya nywele.',
    priceHistory: [{ date: '2026-09-01', price: 90000, changedBy: 'CFO Lilian' }],
    qualifiedStaffIds: ['staff-lilian-zado', 'staff-koku', 'staff-joy'],
    imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Natural Clip-In Blending' },
  },
  {
    id: 'srv-no-leave-out',
    name: 'No Leave Out (Frontal Signature)',
    swahiliName: 'Kufunga Frontal Bila Nywele Zako Kuonekana (No Leave Out)',
    category: 'Installations & Wigs',
    type: 'HD Lace Frontal Melt',
    installationType: 'No Leave Out',
    currentPrice: 280000,
    priceNotConfigured: false,
    durationMinutes: 180,
    depositRequired: 80000,
    durationLabel: '3.0 hrs',
    status: 'Active',
    description: 'FineHair signature lace frontal installation with zero natural hair exposed. Complete skin-melt adhesive application and customized hairline.',
    swahiliDescription: 'Kufunga frontal bila nywele za asili kuonekana, kurekebisha msuko wa kichwa na finishing ya hariri.',
    preparationNotes: 'Leta frontal yako siku 1 kabla kwa ajili ya customization ya lace.',
    aftercareNotes: 'Vaa melt band unapofanya mazoezi; epuka jasho jingi masaa 24 ya kwanza.',
    priceHistory: [{ date: '2026-09-01', price: 280000, changedBy: 'CFO Lilian' }],
    qualifiedStaffIds: ['staff-lilian-zado', 'staff-lilian-john', 'staff-ekilia'],
    imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'HD Lace Melt on Melanin Skin' },
  },
  {
    id: 'srv-wigs',
    name: 'Wigs Custom Fitting & Installation',
    swahiliName: 'Kufunga na Kurekebisha Wigi (Custom Unit Fitting)',
    category: 'Installations & Wigs',
    type: 'Glueless & Melt Wigs',
    currentPrice: 150000,
    priceNotConfigured: false,
    durationMinutes: 120,
    depositRequired: 50000,
    durationLabel: '2.0 hrs',
    status: 'Active',
    description: 'Glueless or adhesive lace melt wig installation, customized hairline plucking, and bespoke head-shaping.',
    swahiliDescription: 'Kufunga wigi kwa umaridadi bila kuumiza ngozi ya mbele.',
    preparationNotes: 'Suka mistari bapa ya ndani (braid down imejumuishwa).',
    aftercareNotes: 'Hifadhi kwa usalama usiku; funga kitambaa cha hariri.',
    priceHistory: [{ date: '2026-09-01', price: 150000, changedBy: 'CFO Collins' }],
    qualifiedStaffIds: ['staff-lilian-zado', 'staff-koku', 'staff-joy'],
    imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Glueless Customized Unit' },
  },
  {
    id: 'srv-wash-blowdry',
    name: 'Wash & Blowdry',
    swahiliName: 'Kuosha na Kukausha kwa Blowdry',
    category: 'Blowdry & Thermal',
    type: 'Wash & Thermal Dry',
    currentPrice: 45000,
    priceNotConfigured: false,
    durationMinutes: 60,
    depositRequired: 15000,
    durationLabel: '1.0 hr',
    status: 'Active',
    description: 'Clarifying wash, scalp massage, hydrating conditioner, and tension blowdry.',
    swahiliDescription: 'Kuosha vizuri na kukausha nywele kwa uangalifu.',
    preparationNotes: 'Hakuna maandalizi maalum.',
    aftercareNotes: 'Tumia serum kuzuia kukauka.',
    priceHistory: [{ date: '2026-09-01', price: 45000, changedBy: 'CFO Lilian' }],
    qualifiedStaffIds: ['staff-jennipher', 'staff-neema', 'staff-morris', 'staff-jesca', 'staff-asia', 'staff-naomi'],
    imageUrl: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Clean Cleansed Afro Hair' },
  },
  {
    id: 'srv-hair-treatment',
    name: 'Intensive Hair Treatment',
    swahiliName: 'Matibabu Maalum ya Kukuza na Kuimarisha Nywele',
    category: 'Treatments & Scalp',
    type: 'Intensive Reconstruction',
    currentPrice: 90000,
    priceNotConfigured: false,
    durationMinutes: 90,
    depositRequired: 30000,
    durationLabel: '1.5 hrs',
    status: 'Active',
    description: 'Bond builder reconstruction for damaged cuticles, chemical damage, and split ends.',
    swahiliDescription: 'Kujenga upya nywele zilizoharibika na dawa au joto.',
    preparationNotes: 'Eleza historia ya kemikali zilizowekwa.',
    aftercareNotes: 'Rudia baada ya wiki nne kwa matokeo bora.',
    priceHistory: [{ date: '2026-09-01', price: 90000, changedBy: 'CFO Collins' }],
    qualifiedStaffIds: ['staff-morris', 'staff-chisomo'],
    imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Deep Reconstructed Strands' },
  },
  {
    id: 'srv-wave-styling',
    name: 'Wave Styling',
    swahiliName: 'Kutengeneza Mawimbi ya Mitindo (Wave Styling)',
    category: 'Styling & Textures',
    type: 'Thermal Curling',
    currentPrice: 65000,
    priceNotConfigured: false,
    durationMinutes: 60,
    depositRequired: 20000,
    durationLabel: '1.0 hr',
    status: 'Active',
    description: 'Beach waves, Hollywood glam waves, and thermal wand curls with flexible holding spray.',
    swahiliDescription: 'Mawimbi ya kifahari kwa ajili ya sherehe au harusi.',
    preparationNotes: 'Nywele ziwe zimenyooka tayari.',
    aftercareNotes: 'Usipake maji; funika kabla ya kulala.',
    priceHistory: [{ date: '2026-09-01', price: 65000, changedBy: 'CFO Lilian' }],
    qualifiedStaffIds: ['staff-asia'],
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Glamour Hollywood Waves' },
  },
  {
    id: 'srv-define-curls',
    name: 'Define Curls (Curl Styling)',
    swahiliName: 'Kuweka Wazi Misokoto ya Asili (Curl Definition)',
    category: 'Styling & Textures',
    type: 'Wash & Go Curl Def',
    currentPrice: 70000,
    priceNotConfigured: false,
    durationMinutes: 90,
    depositRequired: 25000,
    durationLabel: '1.5 hrs',
    status: 'Active',
    description: 'Shingling, raking, and diffuser drying to define natural 3C/4A/4B/4C curl patterns with moisture clumps.',
    swahiliDescription: 'Kufanya misokoto ya asili ionekane wazi na yenye unyevunyevu bila kuweka dawa.',
    preparationNotes: 'Nywele zisinyooshwe kwa joto kabla ya session.',
    aftercareNotes: 'Kausha na diffuser au hewa safi; usivuruge misokoto.',
    priceHistory: [{ date: '2026-09-01', price: 70000, changedBy: 'CFO Collins' }],
    qualifiedStaffIds: ['staff-judy', 'staff-asia'],
    imageUrl: 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Hydrated 4A/4B Defined Curls' },
  },
  {
    id: 'srv-detangling-extensions',
    name: 'Detangling Extensions & Tangle Removal',
    swahiliName: 'Kutoa Mabonge na Kufungua Nywele Zilizojifunga (Detangling)',
    category: 'Treatments & Scalp',
    type: 'Gentle Detangling',
    currentPrice: 55000,
    priceNotConfigured: false,
    durationMinutes: 75,
    depositRequired: 20000,
    durationLabel: '1.2 hrs',
    status: 'Active',
    description: 'Patient, gentle tangle separation using slip-infusion conditioners and wide-tooth bamboo combs to protect natural density.',
    swahiliDescription: 'Kufungua nywele zilizofungamana bila kukata wala kuumiza kichwa.',
    preparationNotes: 'Usilazimishe kuchana nyumbani kwa nguvu kama zimefungana.',
    aftercareNotes: 'Paka detangling milk kabla ya kuchana mara kwa mara.',
    priceHistory: [{ date: '2026-09-01', price: 55000, changedBy: 'CFO Lilian' }],
    qualifiedStaffIds: ['staff-morris', 'staff-chisomo'],
    imageUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=800',
    brandCompliance: { representationVerified: true, hairTexture: 'Gentle Detangled Density' },
  },
];

// -------------------------------------------------------------
// AUTHORITATIVE EXECUTIVE ACCOUNTS (CFO Lilian, CFO Collins, Manager Razaq)
// -------------------------------------------------------------

export interface UserAccount {
  id: string;
  name: string;
  email: string;
  phone?: string;
  role: 'Executive' | 'Manager' | 'Staff' | 'Reception' | 'Marketing' | 'Finance' | 'Customer' | 'System Admin';
  status: 'Active' | 'Pending Invitation' | 'Suspended' | 'Locked' | 'Archived';
  passwordHash?: string;
  passwordSalt?: string;
  mfaEnabled: boolean;
  mfaSecret?: string;
  failedLoginAttempts: number;
  lockedUntil?: string | null;
  branchId: string;
  department: string;
  staffId?: string;
  staffProfileId?: string;
  title: string;
  avatar: string;
  permissions: string[];
  lastLoginAt?: string;
  lastLoginIp?: string;
  createdAt: string;
  updatedAt: string;
}

export const INITIAL_AUTHORITATIVE_USERS: UserAccount[] = [
  {
    id: 'usr-cfo-lilian',
    name: 'CFO Lilian',
    email: 'lilian@finehair.co.tz',
    phone: '+255 742 023 057',
    role: 'Executive',
    status: 'Active',
    passwordHash: hashPassword('FineHair@Lilian2026!', 'salt_lilian_2026').hash,
    passwordSalt: 'salt_lilian_2026',
    mfaEnabled: true,
    mfaSecret: 'FINEHAIR_MFA_LILIAN_CFO',
    failedLoginAttempts: 0,
    lockedUntil: null,
    branchId: 'branch-mikocheni',
    department: 'Executive Board',
    title: 'Chief Financial Officer & Decision Authority',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    permissions: ['*'],
  },
  {
    id: 'usr-cfo-collins',
    name: 'CFO Collins',
    email: 'collins@finehair.co.tz',
    phone: '+255 742 023 058',
    role: 'Executive',
    status: 'Active',
    passwordHash: hashPassword('FineHair@Collins2026!', 'salt_collins_2026').hash,
    passwordSalt: 'salt_collins_2026',
    mfaEnabled: true,
    mfaSecret: 'FINEHAIR_MFA_COLLINS_CFO',
    failedLoginAttempts: 0,
    lockedUntil: null,
    branchId: 'branch-mikocheni',
    department: 'Executive Board',
    title: 'Chief Financial Officer & Executive Controller',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    permissions: ['*'],
  },
  {
    id: 'usr-manager-razaq',
    name: 'Manager Razaq',
    email: 'razaq@finehair.co.tz',
    phone: '+255 742 023 059',
    role: 'Manager',
    status: 'Active',
    passwordHash: hashPassword('FineHair@Razaq2026!', 'salt_razaq_2026').hash,
    passwordSalt: 'salt_razaq_2026',
    mfaEnabled: true,
    mfaSecret: 'FINEHAIR_MFA_RAZAQ_MGR',
    failedLoginAttempts: 0,
    lockedUntil: null,
    branchId: 'branch-mikocheni',
    department: 'Salon Operations',
    title: 'General Salon Operations Manager',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    permissions: [
      'service.read',
      'service.write',
      'price.propose',
      'staff.read',
      'staff.write',
      'appointment.*',
      'customer.*',
      'inventory.*',
      'marketing.write',
      'homepage.write',
      'performance.*',
      'iam.manage_staff',
      'manage_appointments',
      'view_customers',
    ],
  },
];
